* Questions

** Repeat the same text input/deletion (like . in vim)

** Yank and keep point where it is

** Increment and decrement number at point
   http://www.emacswiki.org/emacs/IncrementNumber

** What is the pattern of M & C strokes?

** Are registers permanent?

** What does it mean to bury a buffer?

** How do you customize what delimiters to use in org mode? (See 25.8.1 Format of Outlines)

** Display full file path of current file

** Org seems to be limited to three level deep nesting regarding toggle commands - is this true?

** What are smerge and emerge and diff mode (18.10 - Files)?

** Execute git commands from within emacs

** How to use word wrapping in org mode?

** How do you move a buffer from one window to another?

** Is there an html5 mode - not just xhtml?

** Look up the English definition of the word at point

** How does scroll-conservatively work?

** Does cua-mode Inhibit any commands? (set the variable `cua-enable-cua-keys' to `nil')

** Why isn't flyspell working? Error: No word lists can be found for the language "en_US". M-$

** Is there a way to automate exporting from org mode?


* Todo

** What commands does C-u affect?

** What major/minor modes did I miss?

** Look through the emacs gui context menu

** Figure out how to make completion work

** Find !yt videos regarding the speedbar


* Answers

** Comment Region (M-x comment-region) sucks - it does not use block comments - is there a way to do this?
	 Just use M-; - it comments each line, but that's not so bad

** Change the gui theme
   There is a solarized theme on github, but it looks like a lot of work

** How to prevent emacs from adding newlines at the end of files?
   It doesn't, other than the .emacs files when appending lines

** Jump point up to the first ocurrance of _ character

   C-s CHAR then navigation or deletion command

** Stop emacs from making #filename# files

   (setq make-backup-files nil)
   (setq auto-save-default nil)

** Highlight/jump to paired delimiter
   C-M-n
   C-M-p

** View the current value of a variable
   C-h v <VARIABLE>

** Set up default character encoding and newlines
   C-h C
   The default system encoding is used by default for new files - it does what you would want

** See if the tab issue can be fixed by defining tab width in Terminator
   Tabs are displayed as a certain width by using literal spaces in the terminal. The number of which can be changed by visiting `M-x describe-variable tab-width' and clicking Customize - changes go into the .emacs config file.


* Give Up

** Reset emacs modes to default
