* Questions

** How do you enter recursive editing mode?

** Repeat the same text input/deletion (like . in vim)

** Yank and keep point where it is

** How do you save and exit in one command?

** Increment and decrement number at point
   http://www.emacswiki.org/emacs/IncrementNumber

** What is the pattern of M & C strokes?

** Are registers permanent?

** Abbreviations expand without pressing space?

** How to reverse search immedately rather than redisplaying the current result?

** How do you customize what delimiters to use in org mode? (See 25.8.1 Format of Outlines)

** Display full file path of current file

** Org seems to be limited to three level deep nesting regarding toggle commands - is this true?

** In org mode, is there a way to move a block of items at a time?
	 Make a temporary fake heading at the same level, place a region around said block items, demote them, move block, promote them again, and remove fake header (or leave it for organization purposes)

** What are smerge, emerge, diff and ediff (18.10 - Files)?

** For completion-cycle-threshold, is there a way to display the first complete expansion first, and then the rest of the full expansions?

** In dired, how do you stop new buffers from being created for every directory visited?

** In dired, how do you perform version control actions on marked files?

** Is there a reason that TAGS files should be on disk?
	 Can't etags be executed on the contents of the emacs buffer?

** What are `alist's, and how do you use them? For example, prettify-symbols-alist.

** How to use word wrapping in org mode?

** How do you move a buffer from one window to another?

** Is there an html5 mode - not just xhtml?

** Why do async shell commands not use zshrc/bashrc file?

** Look up the English definition of the word at point

** How does scroll-conservatively work?

** Does cua-mode Inhibit any commands? (set the variable `cua-enable-cua-keys' to `nil')

** Why isn't flyspell working? Error: No word lists can be found for the language "en_US". M-$

** Flymake is broken, too. Useful for HTML?

** Is there a way to automate exporting from org mode?


* Todo

** Find !yt video on how to use git vc integration

** What commands does C-u affect?

** What major/minor modes did I miss?

** Look through the emacs gui context menu

** Figure out how to make completion work (semantic-mode? 26.10)

** Figure out how to make vc filesets

** Find !yt videos regarding the speedbar

** Don't forget about Autotyping (Top in Info under Emacs)


* Hooks to Utilize

** Programming major modes should have the following modes enabled
	 semantic-mode
	 electric-layout-mode
	 rainbow-delimiters


* Answers

** Execute git commands from within emacs
	 C-x v v
	 C-x v G
	 Beware, some commands don't do what you would expect - gitignore does not use full path

** What does it mean to bury a buffer?
	 It's like switching tabs. Buried buffers can be found with C-x C-b.

** In dired, how do you prevent ls from displaying . & ..?
	 (setq-default dired-listing-switches "-Alh")

** In dired, how do you open a file and bury it immediately? (Good for opening multiple files at once.)
	 Mark multiple files and open all of them at once

** Comment Region (M-x comment-region) sucks - it does not use block comments - is there a way to do this?
	 Just use M-; - it comments each line, but that's not so bad

** Change the gui theme
   There is a solarized theme on github, but it looks like a lot of work

** How to prevent emacs from adding newlines at the end of files?
   It doesn't, other than the .emacs files when appending lines

** Jump point up to the first ocurrance of _ character

   C-s CHAR then navigation or deletion command

** Stop emacs from making #filename# files

   (setq make-backup-files nil)
   (setq auto-save-default nil)

** Highlight/jump to paired delimiter
   C-M-n
   C-M-p

** View the current value of a variable
   C-h v <VARIABLE>

** Set up default character encoding and newlines
   C-h C
   The default system encoding is used by default for new files - it does what you would want

** See if the tab issue can be fixed by defining tab width in Terminator
   Tabs are displayed as a certain width by using literal spaces in the terminal. The number of which can be changed by visiting `M-x describe-variable tab-width' and clicking Customize - changes go into the .emacs config file.


* Give Up

** Reset emacs modes to default
