* Questions

** How do you jump to matching delimiter?

** How do you wrap a closing delimiter around the specified number of sub-delimitered content (M-4 \( ?)

** How to redefine formatting rules for specific languages - Lisp & JavaScript in particular

** How do you save and exit in one command?

** Mark paragraph from first non-newline to all trailing newlines?

** For completion-cycle-threshold, is there a way to display the first complete expansion first, and then the rest of the full expansions?

** Lisp syntax highlighting

** Is it possible to set emacs to kill buffers (like *Appropos* or *Buffer List*) upon pressing q?

** Yank and keep point where it is

** Insert characters and keep point where it is

** Copy text from point to end of line

** Increment and decrement number at point
   http://www.emacswiki.org/emacs/IncrementNumber

** How do you commit multiple files at once? Dired? (git)

** How do you enter recursive editing mode?

** How do you delete an active region when a character is inserted?

** Are registers permanent?

** Is there a way to transpose the current line and the line above rather than the two lines above?

** Abbreviations expand without pressing space?

** How to reverse search immedately rather than redisplaying the current result?

** How do you customize what delimiters to use in org mode? (See 25.8.1 Format of Outlines)

** How do you delete all whitespace around point?

** Is there a method of displaying version control local changes in dired?

** Is there a technique for visually customizing the color theme?

** Is there a way to drag a region of lines around like you do with C-x C-t?

** Display full file path of current file

** Electric pair mode only if the next character is whitespace?

** What are smerge, emerge, diff and ediff (18.10 - Files)?

** Is there a way to make the screen flash less contrasty?

** Is there a way to change from flattened undo history to tree history?

** What is the pattern of M & C strokes?

** How do you move a buffer from one window to another?

** Why do async shell commands not use zshrc/bashrc file?

** In dired, how do you stop new buffers from being created for every directory visited?

** In dired, how do you perform version control actions on marked files?

** Is there a reason that TAGS files should be on disk?
	 Can't etags be executed on the contents of the emacs buffer?

** What are `alist's, and how do you use them? For example, prettify-symbols-alist.

** Org seems to be limited to three level deep nesting regarding toggle commands - is this true?

** In org mode, is there a way to move a block of items at a time?
	 Make a temporary fake heading at the same level, place a region around said block items, demote them, move block, promote them again, and remove fake header (or leave it for organization purposes)

** How to use word wrapping in org mode?

** Is there an html5 mode - not just xhtml?

** Is there a way to move blocks of lines up and down with regions or something?

** Why do commands work differently in the gui vs the shell? For example, C-<RET> in org mode.

** What is the best way to set a rectangular region around one column and the absolute right-most portion of the buffer?

** Is it possible to narrow to a rectangular region?

** Is there a way to edit documents on a remote server with a locally running version of emacs?

** Look up the English definition of the word at point

** What the heck is emacs server? (see 38)

** How does scroll-conservatively work?

** Does cua-mode Inhibit any commands? (set the variable `cua-enable-cua-keys' to `nil')

** Why isn't flyspell working? Error: No word lists can be found for the language "en_US". M-$

** Flymake is broken, too. Useful for HTML?

** Is there a way to automate exporting from org mode?


* Answers

** How do you set tab width? (I prefer tabs and two spaces per tab displayed)
	 M-x customize-browse
	 Emacs > Editing > Indent

** Figure out how to make completion work (semantic-mode? 26.10)
	 M-/
	 Tags are weird - not sure quite how to use them

** Execute git commands from within emacs
	 C-x v v
	 C-x v G
	 Beware, some commands don't do what you would expect - gitignore does not use full path

** What does it mean to bury a buffer?
	 It's like switching tabs. Buried buffers can be found with C-x C-b.

** In dired, how do you prevent ls from displaying . & ..?
	 (setq-default dired-listing-switches "-Alh")

** In dired, how do you open a file and bury it immediately? (Good for opening multiple files at once.)
	 Mark multiple files and open all of them at once

** Comment Region (M-x comment-region) sucks - it does not use block comments - is there a way to do this?
	 Just use M-; - it comments each line, but that's not so bad

** Change the gui theme
   There is a solarized theme on github, but it looks like a lot of work

** How to prevent emacs from adding newlines at the end of files?
   It doesn't, other than the .emacs files when appending lines

** Jump point up to the first ocurrance of _ character

   C-s CHAR then navigation or deletion command

** Stop emacs from making #filename# files

   (setq make-backup-files nil)
   (setq auto-save-default nil)

** Highlight/jump to paired delimiter
   C-M-n
   C-M-p

** View the current value of a variable
   C-h v <VARIABLE>

** Set up default character encoding and newlines
   C-h C
   The default system encoding is used by default for new files - it does what you would want

** See if the tab issue can be fixed by defining tab width in Terminator
   Tabs are displayed as a certain width by using literal spaces in the terminal. The number of which can be changed by visiting `M-x describe-variable tab-width' and clicking Customize - changes go into the .emacs config file.

** Repeat the same text input/deletion (like . in vim)
	 Yes! http://www.emacswiki.org/emacs/dot-mode.el

